export const images = [
{ "name": "1.jpg",
  "top": "30%",
  "left": "50%",
  "opacity": "0.5",
  "font-size": "40px",
  "traslatex": "-50%",
  "traslatey": "-50%",
},
{ "name": "2.jpg",
  "top": "30%",
  "left": "50%",
  "opacity": "0.5",
  "font-size": "40px",
  "traslatex": "-50%",  
  "traslatey": "-50%",  
},
{ "name": "3.jpg",
  "top": "30%",
  "left": "50%",
  "opacity": "0.4",
  "font-size": "40px",
  "traslatex": "-50%",  
  "traslatey": "-50%",  
  "tag": "na"
},
{ "name": "4.jpg",
  "top": "30%",
  "left": "50%",
  "opacity": "0.5",
  "font-size": "40px",
  "traslatex": "-50%",  
  "traslatey": "-50%",  
  "tag": "na"
},
{ "name": "5.jpg",
  "top": "30%",
  "left": "50%",
  "opacity": "0.5",
  "font-size": "40px",
  "traslatex": "-50%",  
  "traslatey": "-50%",  
  "tag": "na"
},
{ "name": "6.jpg",
  "top": "30%",
  "left": "50%",
  "opacity": "0.3",
  "font-size": "40px",
  "traslatex": "-50%",  
  "traslatey": "-50%",  
  "tag": "na"
},
{ "name": "7.jpg",
  "top": "30%",
  "left": "50%",
  "opacity": "0.4",
  "font-size": "40px",
  "traslatex": "-50%",  
  "traslatey": "-50%",  
  "tag": "na"
},
{ "name": "8.jpg",
  "top": "30%",
  "left": "50%",
  "opacity": "0.5",
  "font-size": "40px",
  "traslatex": "-50%",  
  "traslatey": "-50%",  
  "tag": "na"
},
{ "name": "9.jpg",
  "top": "30%",
  "left": "50%",
  "opacity": "0.4",
  "font-size": "40px",
  "traslatex": "-50%",  
  "traslatey": "-50%",  
  "tag": "na"
},
{ "name": "10.jpg",
  "top": "30%",
  "left": "50%",
  "opacity": "0.4",
  "font-size": "40px",
  "traslatex": "-50%",  
  "traslatey": "-50%",  
  "tag": "na"
},
{ "name": "11.jpg",
  "top": "30%",
  "left": "50%",
  "opacity": "0.5",
  "font-size": "40px",
  "traslatex": "-50%",  
  "traslatey": "-50%",  
  "tag": "na"
},
{ "name": "12.png",
  "top": "30%",
  "left": "50%",
  "opacity": "0.5",
  "font-size": "40px",
  "traslatex": "-50%",  
  "traslatey": "-50%",  
  "tag": "na"
},
{ "name": "13.jpg",
  "top": "30%",
  "left": "50%",
  "opacity": "0.5",
  "font-size": "40px",
  "traslatex": "-50%",  
  "traslatey": "-50%",  
  "tag": "na"
},
{ "name": "14.jpg",
  "top": "30%",
  "left": "50%",
  "opacity": "0.4",
  "font-size": "40px",
  "traslatex": "-50%",  
  "traslatey": "-50%",  
  "tag": "na"
},
{ "name": "15.jpg",
  "top": "30%",
  "left": "50%",
  "opacity": "0.4",
  "font-size": "40px",
  "traslatex": "-50%",  
  "traslatey": "-50%",  
  "tag": "na"
},
{ "name": "16.jpg",
  "top": "30%",
  "left": "50%",
  "opacity": "0.4",
  "font-size": "40px",
  "traslatex": "-50%",  
  "traslatey": "-50%",  
  "tag": "na"
},
{ "name": "17.jpg",
  "top": "30%",
  "left": "50%",
  "opacity": "0.4",
  "font-size": "40px",
  "traslatex": "-50%",  
  "traslatey": "-50%",  
  "tag": "na"
},
{ "name": "18.jpg",
  "top": "30%",
  "left": "50%",
  "opacity": "0.4",
  "font-size": "40px",
  "traslatex": "-50%",  
  "traslatey": "-50%",  
  "tag": "na"
},
{ "name": "19.jpg",
  "top": "30%",
  "left": "50%",
  "opacity": "0.4",
  "font-size": "40px",
  "traslatex": "-50%",  
  "traslatey": "-50%",  
  "tag": "na"
},
{ "name": "20.jpg",
  "top": "30%",
  "left": "50%",
  "opacity": "0.4",
  "font-size": "40px",
  "traslatex": "-50%",  
  "traslatey": "-50%",  
  "tag": "na"
},
];
